# Generated by Django 4.1.3 on 2023-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_project_link_remove_project_name_project_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='name',
        ),
        migrations.AddField(
            model_name='publication',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
