# Generated by Django 4.1.3 on 2023-01-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_publication_name_publication_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copyright',
            old_name='title',
            new_name='data',
        ),
        migrations.AddField(
            model_name='copyright',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
