# Generated by Django 4.1.3 on 2023-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_title_copyright_data_copyright_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar',
            old_name='youtube_embed_link',
            new_name='youtube_embed_code',
        ),
        migrations.AlterField(
            model_name='copyright',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
