# Generated by Django 4.1.3 on 2023-01-22 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_youtube_embed_link_webinar_youtube_embed_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReviewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='This will be rendered as html in the frontend', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='This will be rendered as html in the frontend', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalIV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='This will be rendered as html in the frontend', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='This will be rendered as html in the frontend', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_work', models.CharField(choices=[('Resource Person', 'Resource Person'), ('Organized', 'Organized'), ('Attended', 'Attended')], default='Organized', max_length=255)),
                ('data', models.TextField(help_text='This will be rendered as html in the frontend', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperReviewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='This will be rendered as html in the frontend', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='This will be rendered as html in the frontend', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='This will be rendered as html in the frontend', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(help_text='This is an html rendered field, you can add anchor and paragraph tags here. This will be rendered to the frontend', on_delete=django.db.models.deletion.CASCADE, to='main.projecttype'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='data',
            field=models.TextField(help_text='This is an html rendered field, you can add anchor and paragraph tags here. This will be rendered to the frontend', null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='youtube_embed_code',
            field=models.CharField(help_text='Please enter the youtube embed code, it will look like "2fIo1WH5bcg", please do not enter all the embed code.', max_length=255, null=True),
        ),
    ]
