# Generated by Django 4.1.3 on 2023-01-22 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bookreviewed_curriculumdevelopment_internationaliv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherMembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='This is an html rendered field, you can add anchor and paragraph tags here. This will be rendered to the frontend', null=True)),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.othermembershiptype')),
            ],
        ),
    ]
