# Generated by Django 4.1.3 on 2023-03-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_researchgrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture_extra',
            field=models.ImageField(null=True, upload_to='static/images/books/'),
        ),
    ]
