# Generated by Django 4.1.3 on 2023-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_book_picture_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookaccomplishment',
            name='point',
            field=models.TextField(null=True),
        ),
    ]
