# Generated by Django 3.2.12 on 2023-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_bookaccomplishment_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='uploads/')),
                ('Img1', models.ImageField(upload_to='uploads/')),
                ('Img2', models.ImageField(upload_to='uploads/')),
                ('Img3', models.ImageField(upload_to='uploads/')),
                ('Img4', models.ImageField(upload_to='uploads/')),
                ('Img5', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
