# Generated by Django 4.1.3 on 2023-05-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_slideshow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slideshow',
            old_name='Img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='slideshow',
            old_name='Img1',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='slideshow',
            old_name='Img2',
            new_name='img2',
        ),
        migrations.RenameField(
            model_name='slideshow',
            old_name='Img3',
            new_name='img3',
        ),
        migrations.RenameField(
            model_name='slideshow',
            old_name='Img4',
            new_name='img4',
        ),
        migrations.RenameField(
            model_name='slideshow',
            old_name='Img5',
            new_name='img5',
        ),
    ]
