# Generated by Django 4.1.6 on 2023-05-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_slideshow_img_alter_slideshow_img1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='img5',
        ),
    ]
