# Generated by Django 4.1.6 on 2023-05-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_slideshow_img1_slideshow_img2_slideshow_img3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='img',
            field=models.ImageField(upload_to='static/images/events/default.jpeg'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='img1',
            field=models.ImageField(upload_to='static/images/events/default2.jpeg'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='img2',
            field=models.ImageField(upload_to='static/images/events/default3.jpeg'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='img3',
            field=models.ImageField(upload_to='static/images/events/default4.jpeg'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='img4',
            field=models.ImageField(upload_to='static/images/events/default5.jpeg'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='img5',
            field=models.ImageField(upload_to='static/images/events/default6.jpeg'),
        ),
    ]
