# Generated by Django 4.1.6 on 2023-06-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_slideshow_img_alter_slideshow_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='contact_me',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
