# Generated by Django 4.1.6 on 2023-06-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_book_contact_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='contact_me',
        ),
    ]
