# Generated by Django 4.2.1 on 2023-06-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Intro',
        ),
    ]
