# Generated by Django 4.2.1 on 2023-06-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_home_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
