# Generated by Django 4.2.1 on 2023-06-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_intro_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Av',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/uploads')),
            ],
        ),
    ]
