# Generated by Django 4.2.1 on 2023-06-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_av_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='getfrom1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='getfrom1_link',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='getfrom2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='getfrom2_link',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='getfrom3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='getfrom3_link',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
